name: Build Frontend Assets

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'public/build/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Show generated assets
        run: |
          ls -la public || true
          ls -la public/build || true
      - name: Force-commit built assets (public/build)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f public/build
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci(build): commit public/build assets [skip ci]"
            # Avoid loops: only build/ changed and paths-ignore prevents re-run
            git push origin HEAD
          fi
