name: Build Frontend Assets

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'public/build/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit built assets (public/build)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(build): commit public/build assets [skip ci]"
          file_pattern: public/build/**/*
          add_options: '-f'
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          push_options: '--force-with-lease'

