name: Deploy to Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TARGET_DIR: ${{ secrets.TARGET_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install JS deps
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: mbstring, intl, pdo_mysql

      - name: Install PHP deps
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: SSH update code and caches (pull + migrate)
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            mkdir -p "${TARGET_DIR}"
            if [ ! -d "${TARGET_DIR}/.git" ]; then
              git clone https://github.com/${{ github.repository }}.git "${TARGET_DIR}"
            fi
            cd "${TARGET_DIR}"
            git fetch origin
            git checkout main
            git pull --ff-only origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force || true
            # Ensure base categories exist (idempotent)
            php artisan db:seed --class="Database\\Seeders\\CategoriaSeeder" --force || true
            php artisan optimize:clear || true
            php artisan config:cache || true
            php artisan route:cache || true
            php artisan view:clear || true
            php artisan storage:link || true

      - name: Upload built assets to server (optional)
        if: always()
        continue-on-error: true
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/build/**"
          target: "${{ env.TARGET_DIR }}"
